# Generated by Django 2.1.3 on 2018-12-01 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('lineId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.IntegerField(choices=[(1, 'Init'), (2, 'Deal'), (3, 'Done')])),
                ('picture', models.ImageField(upload_to='static/')),
                ('qty_can', models.IntegerField(default=0)),
                ('qty_bottle', models.IntegerField(default=0)),
                ('qty_glass', models.IntegerField(default=0)),
                ('tot_price', models.IntegerField()),
                ('buyer_lineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getridchApp.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('lineId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='seller_lineId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getridchApp.Seller'),
        ),
    ]
